# Generated by Django 5.2.1 on 2025-05-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullName", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("mobile", models.CharField(max_length=10)),
                ("whatsapp", models.CharField(max_length=10)),
                ("dob", models.CharField(max_length=10)),
                ("location", models.CharField(max_length=20)),
                ("willingToRelocate", models.BooleanField()),
                ("education", models.CharField(max_length=100)),
                ("institution", models.CharField(max_length=100)),
                ("hobbies", models.CharField(max_length=100)),
                ("futurePlan", models.CharField(max_length=100)),
                ("fatherOccupation", models.CharField(max_length=100)),
                ("isFresher", models.BooleanField()),
                (
                    "experience_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "experience_description",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "experience_brief",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("currentCTC", models.CharField(blank=True, max_length=30, null=True)),
                ("expectedCTC", models.CharField(blank=True, max_length=30, null=True)),
                ("resume", models.FileField(upload_to="resume/")),
            ],
        ),
    ]
