# Generated by Django 5.2.1 on 2025-05-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_jobapplication"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="role",
            field=models.CharField(default="Technical Expert", max_length=100),
            preserve_default=False,
        ),
    ]
