# Generated by Django 5.2.1 on 2025-05-19 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_jobapplication_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_application",
                to="app.joblisting",
            ),
        ),
    ]
