# Generated by Django 5.2.1 on 2025-05-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_jobapplication_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="joblisting",
            name="icon",
        ),
        migrations.AddField(
            model_name="joblisting",
            name="image",
            field=models.ImageField(default="image.jpg", upload_to="job_role/"),
            preserve_default=False,
        ),
    ]
