# Generated by Django 5.2.1 on 2025-05-20 05:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_remove_joblisting_icon_joblisting_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="joblisting",
            name="created_at",
            field=models.DateField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 5, 20, 5, 45, 18, 916818, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
