# Generated by Django 5.2.1 on 2025-05-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_joblisting_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="status",
            field=models.CharField(
                choices=[("Key 1", "Value 1")], default="Key 1", max_length=100
            ),
            preserve_default=False,
        ),
    ]
