# Generated by Django 5.2.1 on 2025-05-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_jobapplication_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="joblisting",
            name="status",
            field=models.CharField(default="active", max_length=100),
        ),
    ]
