# Generated by Django 5.2.1 on 2025-05-20 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_alter_jobapplication_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="created_at",
            field=models.DateField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 5, 20, 8, 59, 40, 796427, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
