# Generated by Django 5.2.1 on 2025-05-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_jobapplication_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Screened", "Screened"),
                    ("Short listed", "Short listed"),
                    ("Addressed", "Addressed"),
                    ("Task Assigned", "Task Assigned"),
                    ("Task Completed", "Task Completed"),
                    ("Internship Started", "Internship Started"),
                    ("Internship Completed", "Internship Completed"),
                    ("Onboarded", "Onboarded"),
                    ("Rejected", "Rejected"),
                    ("Held for Review", "Held for Review"),
                    ("Terminated", "Terminated"),
                    ("Relieved", "Relieved"),
                    ("RNR", "RNR"),
                    ("NR", "NR"),
                    ("CBL", "CBL"),
                ],
                default="Pending",
                max_length=100,
            ),
        ),
    ]
