# Generated by Django 5.2.1 on 2025-05-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_alter_jobapplication_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="notes",
            field=models.TextField(default="ZNotes"),
            preserve_default=False,
        ),
    ]
