# Generated by Django 5.2.1 on 2025-05-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_alter_jobapplication_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="joblisting",
            name="is_internship",
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
