# Generated by Django 5.2.1 on 2025-05-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_joblisting_is_internship"),
    ]

    operations = [
        migrations.AddField(
            model_name="joblisting",
            name="custom_fields",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
