# Generated by Django 5.2.1 on 2025-05-21 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_joblisting_custom_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="custom_fields",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
