# Generated by Django 5.2.1 on 2025-05-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_jobapplication_custom_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="gallery/")),
                ("alt", models.CharField(blank=True, max_length=255)),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
            ],
        ),
    ]
