# Generated by Django 5.2.1 on 2025-05-27 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_gallery"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gallery",
            name="height",
        ),
        migrations.RemoveField(
            model_name="gallery",
            name="width",
        ),
    ]
